namespace DesktopApp_Project.GUI
{
    partial class FrmHocVien
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label _lblTitle;
        private System.Windows.Forms.Label _lblDesigner8;
        private System.Windows.Forms.Label _lblDesigner7;
        private System.Windows.Forms.Label _lblDesigner6;
        private System.Windows.Forms.Label _lblDesigner5;
        private System.Windows.Forms.Label _lblDesigner4;
        private System.Windows.Forms.Label _lblDesigner3;
        private System.Windows.Forms.Label _lblDesigner2;
        private System.Windows.Forms.Label _lblDesigner1;
        private System.Windows.Forms.TableLayoutPanel root;
        private System.Windows.Forms.FlowLayoutPanel search;
        private System.Windows.Forms.Button btnTim;
        private System.Windows.Forms.TableLayoutPanel form;
        private System.Windows.Forms.FlowLayoutPanel buttons;
        private System.Windows.Forms.Button btnThem;
        private System.Windows.Forms.Button btnLuu;
        private System.Windows.Forms.Button btnXoa;
        private System.Windows.Forms.DataGridView _grid;
        private System.Windows.Forms.TextBox _txtTim;
        private System.Windows.Forms.TextBox _txtHoTen;
        private System.Windows.Forms.TextBox _txtSdt;
        private System.Windows.Forms.TextBox _txtEmail;
        private System.Windows.Forms.TextBox _txtTrinhDo;
        private System.Windows.Forms.TextBox _txtTaiKhoan;
        private System.Windows.Forms.TextBox _txtMatKhau;
        private System.Windows.Forms.DateTimePicker _dtNgaySinh;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this._lblTitle = new System.Windows.Forms.Label();
            this._lblTitle.AutoEllipsis = true;
            this._lblTitle.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this._lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this._lblTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this._lblTitle.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._lblTitle.Margin = new System.Windows.Forms.Padding(0);
            this._lblTitle.Name = "_lblTitle";
            this._lblTitle.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this._lblTitle.Text = "Quản lý hồ sơ học viên";
            this._lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._lblDesigner8 = new System.Windows.Forms.Label();
            this._lblDesigner8.Text = "Mật khẩu";
            this._lblDesigner8.AutoSize = true;
            this._lblDesigner7 = new System.Windows.Forms.Label();
            this._lblDesigner7.Text = "Tài khoản";
            this._lblDesigner7.AutoSize = true;
            this._lblDesigner6 = new System.Windows.Forms.Label();
            this._lblDesigner6.Text = "Trình độ đầu vào";
            this._lblDesigner6.AutoSize = true;
            this._lblDesigner5 = new System.Windows.Forms.Label();
            this._lblDesigner5.Text = "Email";
            this._lblDesigner5.AutoSize = true;
            this._lblDesigner4 = new System.Windows.Forms.Label();
            this._lblDesigner4.Text = "SĐT";
            this._lblDesigner4.AutoSize = true;
            this._lblDesigner3 = new System.Windows.Forms.Label();
            this._lblDesigner3.Text = "Ngày sinh";
            this._lblDesigner3.AutoSize = true;
            this._lblDesigner2 = new System.Windows.Forms.Label();
            this._lblDesigner2.Text = "Họ tên";
            this._lblDesigner2.AutoSize = true;
            this._lblDesigner1 = new System.Windows.Forms.Label();
            this._lblDesigner1.Text = "Từ khóa";
            this._lblDesigner1.AutoSize = true;
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AutoGenerateColumns = true;
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._grid.BackgroundColor = System.Drawing.Color.White;
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this._grid.ColumnHeadersHeight = 34;
            this._grid.Dock = System.Windows.Forms.DockStyle.Fill;
            this._grid.EnableHeadersVisualStyles = false;
            this._grid.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._grid.GridColor = System.Drawing.Color.FromArgb(213, 220, 230);
            this._grid.MinimumSize = new System.Drawing.Size(320, 180);
            this._grid.MultiSelect = false;
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.RowTemplate.Height = 30;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._txtTim = new System.Windows.Forms.TextBox();
            this._txtTim.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtTim.BackColor = System.Drawing.Color.White;
            this._txtTim.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTim.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtTim.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtTim.Margin = new System.Windows.Forms.Padding(4);
            this._txtTim.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtTim.Width = 220;
            this._txtHoTen = new System.Windows.Forms.TextBox();
            this._txtHoTen.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtHoTen.BackColor = System.Drawing.Color.White;
            this._txtHoTen.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtHoTen.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtHoTen.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtHoTen.Margin = new System.Windows.Forms.Padding(4);
            this._txtHoTen.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtHoTen.Width = 220;
            this._txtSdt = new System.Windows.Forms.TextBox();
            this._txtSdt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtSdt.BackColor = System.Drawing.Color.White;
            this._txtSdt.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtSdt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtSdt.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtSdt.Margin = new System.Windows.Forms.Padding(4);
            this._txtSdt.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtSdt.Width = 220;
            this._txtEmail = new System.Windows.Forms.TextBox();
            this._txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtEmail.BackColor = System.Drawing.Color.White;
            this._txtEmail.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtEmail.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtEmail.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtEmail.Margin = new System.Windows.Forms.Padding(4);
            this._txtEmail.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtEmail.Width = 220;
            this._txtTrinhDo = new System.Windows.Forms.TextBox();
            this._txtTrinhDo.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtTrinhDo.BackColor = System.Drawing.Color.White;
            this._txtTrinhDo.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTrinhDo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtTrinhDo.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtTrinhDo.Margin = new System.Windows.Forms.Padding(4);
            this._txtTrinhDo.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtTrinhDo.Width = 220;
            this._txtTaiKhoan = new System.Windows.Forms.TextBox();
            this._txtTaiKhoan.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtTaiKhoan.BackColor = System.Drawing.Color.White;
            this._txtTaiKhoan.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTaiKhoan.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtTaiKhoan.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtTaiKhoan.Margin = new System.Windows.Forms.Padding(4);
            this._txtTaiKhoan.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtTaiKhoan.Width = 220;
            this._txtMatKhau = new System.Windows.Forms.TextBox();
            this._txtMatKhau.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtMatKhau.BackColor = System.Drawing.Color.White;
            this._txtMatKhau.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtMatKhau.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtMatKhau.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtMatKhau.Margin = new System.Windows.Forms.Padding(4);
            this._txtMatKhau.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtMatKhau.Width = 220;
            this._dtNgaySinh = new System.Windows.Forms.DateTimePicker();
            this.root = new System.Windows.Forms.TableLayoutPanel();
            this.search = new System.Windows.Forms.FlowLayoutPanel();
            this.btnTim = new System.Windows.Forms.Button();
            this.btnTim.AutoEllipsis = true;
            this.btnTim.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnTim.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnTim.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnTim.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTim.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnTim.Height = 34;
            this.btnTim.Margin = new System.Windows.Forms.Padding(4);
            this.btnTim.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnTim.UseVisualStyleBackColor = false;
            this.btnTim.Width = 110;
            this.btnTim.Text = "Tìm kiếm";
            this.form = new System.Windows.Forms.TableLayoutPanel();
            this.form.AutoSize = true;
            this.form.BackColor = System.Drawing.Color.White;
            this.form.ColumnCount = 4;
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.form.Dock = System.Windows.Forms.DockStyle.Top;
            this.form.GrowStyle = System.Windows.Forms.TableLayoutPanelGrowStyle.AddRows;
            this.form.Margin = new System.Windows.Forms.Padding(0);
            this.form.Padding = new System.Windows.Forms.Padding(12, 10, 12, 10);
            this.buttons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnThem = new System.Windows.Forms.Button();
            this.btnThem.AutoEllipsis = true;
            this.btnThem.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnThem.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThem.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnThem.Height = 34;
            this.btnThem.Margin = new System.Windows.Forms.Padding(4);
            this.btnThem.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnThem.UseVisualStyleBackColor = false;
            this.btnThem.Width = 110;
            this.btnThem.Text = "Thêm mới";
            this.btnLuu = new System.Windows.Forms.Button();
            this.btnLuu.AutoEllipsis = true;
            this.btnLuu.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnLuu.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuu.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLuu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLuu.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnLuu.Height = 34;
            this.btnLuu.Margin = new System.Windows.Forms.Padding(4);
            this.btnLuu.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnLuu.UseVisualStyleBackColor = false;
            this.btnLuu.Width = 110;
            this.btnLuu.Text = "Lưu";
            this.btnXoa = new System.Windows.Forms.Button();
            this.btnXoa.AutoEllipsis = true;
            this.btnXoa.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnXoa.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnXoa.Height = 34;
            this.btnXoa.Margin = new System.Windows.Forms.Padding(4);
            this.btnXoa.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnXoa.UseVisualStyleBackColor = false;
            this.btnXoa.Width = 110;
            this.btnXoa.Text = "Xóa";
            this.root.SuspendLayout();
            this.search.SuspendLayout();
            this.form.SuspendLayout();
            this.buttons.SuspendLayout();
            this.SuspendLayout();

            this.root.Dock = System.Windows.Forms.DockStyle.Fill;
            this.root.RowCount = 4;
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));

            this.search.Dock = System.Windows.Forms.DockStyle.Top;
            this.search.AutoSize = true;
            this.search.Padding = new System.Windows.Forms.Padding(8);
            this.search.Controls.Add(this._lblDesigner1);
            this.search.Controls.Add(this._txtTim);
            this.search.Controls.Add(this.btnTim);

            this._dtNgaySinh.Width = 220;
            this._dtNgaySinh.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this._dtNgaySinh.CustomFormat = "dd/MM/yyyy";
            this._dtNgaySinh.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;

            this.form.Controls.Add(this._lblDesigner2, 0, 0);
            this.form.Controls.Add(this._txtHoTen, 1, 0);
            this.form.Controls.Add(this._lblDesigner3, 2, 0);
            this.form.Controls.Add(this._dtNgaySinh, 3, 0);
            this.form.Controls.Add(this._lblDesigner4, 0, 1);
            this.form.Controls.Add(this._txtSdt, 1, 1);
            this.form.Controls.Add(this._lblDesigner5, 2, 1);
            this.form.Controls.Add(this._txtEmail, 3, 1);
            this.form.Controls.Add(this._lblDesigner6, 0, 2);
            this.form.Controls.Add(this._txtTrinhDo, 1, 2);
            this.form.Controls.Add(this._lblDesigner7, 2, 2);
            this.form.Controls.Add(this._txtTaiKhoan, 3, 2);
            this.form.Controls.Add(this._lblDesigner8, 0, 3);
            this.form.Controls.Add(this._txtMatKhau, 1, 3);

            this.buttons.Dock = System.Windows.Forms.DockStyle.Top;
            this.buttons.AutoSize = true;
            this.buttons.Controls.Add(this.btnThem);
            this.buttons.Controls.Add(this.btnLuu);
            this.buttons.Controls.Add(this.btnXoa);
            this.form.Controls.Add(this.buttons, 3, 3);

            this.btnTim.Click += this.BtnTim_Click;
            this.btnThem.Click += this.BtnThem_Click;
            this.btnLuu.Click += this.BtnLuu_Click;
            this.btnXoa.Click += this.BtnXoa_Click;
            this._grid.SelectionChanged += this.Grid_SelectionChanged;
            this.root.Controls.Add(this._lblTitle, 0, 0);

            this.root.Controls.Add(this.search, 0, 1);
            this.root.Controls.Add(this.form, 0, 2);
            this.root.Controls.Add(this._grid, 0, 3);

            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 720);
            this.Name = "FrmHocVien";
            this.Controls.Add(this.root);

            this.root.ResumeLayout(false);
            this.root.PerformLayout();
            this.search.ResumeLayout(false);
            this.search.PerformLayout();
            this.form.ResumeLayout(false);
            this.form.PerformLayout();
            this.buttons.ResumeLayout(false);
            this.buttons.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
    }
}
