namespace DesktopApp_Project.GUI
{
    partial class FrmLopHoc
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label _lblTitle;
        private System.Windows.Forms.Label _lblDesigner3;
        private System.Windows.Forms.Label _lblDesigner2;
        private System.Windows.Forms.Label _lblDesigner1;
        private System.Windows.Forms.Label _lblHuongDanPhanLop;
        private System.Windows.Forms.TableLayoutPanel root;
        private System.Windows.Forms.TableLayoutPanel form;
        private System.Windows.Forms.FlowLayoutPanel buttons;
        private System.Windows.Forms.Button btnThem;
        private System.Windows.Forms.Button btnLuu;
        private System.Windows.Forms.Button btnXoa;
        private System.Windows.Forms.Panel bottom;
        private System.Windows.Forms.TableLayoutPanel split;
        private System.Windows.Forms.FlowLayoutPanel assignButtons;
        private System.Windows.Forms.Button btnThemHv;
        private System.Windows.Forms.Button btnXoaHv;
        private System.Windows.Forms.DataGridView _gridLop;
        private System.Windows.Forms.DataGridView _gridTrongLop;
        private System.Windows.Forms.DataGridView _gridNgoaiLop;
        private System.Windows.Forms.TextBox _txtTenLop;
        private System.Windows.Forms.TextBox _txtTrinhDo;
        private System.Windows.Forms.TextBox _txtLichHoc;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this._lblTitle = new System.Windows.Forms.Label();
            this._lblTitle.AutoEllipsis = true;
            this._lblTitle.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this._lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this._lblTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this._lblTitle.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._lblTitle.Margin = new System.Windows.Forms.Padding(0);
            this._lblTitle.Name = "_lblTitle";
            this._lblTitle.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this._lblTitle.Text = "Quản lý lớp học";
            this._lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._lblDesigner3 = new System.Windows.Forms.Label();
            this._lblDesigner3.Text = "Lịch học";
            this._lblDesigner3.AutoSize = true;
            this._lblDesigner2 = new System.Windows.Forms.Label();
            this._lblDesigner2.Text = "Nhóm trình độ";
            this._lblDesigner2.AutoSize = true;
            this._lblDesigner1 = new System.Windows.Forms.Label();
            this._lblDesigner1.Text = "Tên lớp";
            this._lblDesigner1.AutoSize = true;
            this._lblHuongDanPhanLop = new System.Windows.Forms.Label();
            this._lblHuongDanPhanLop.Text = "Bên trái: học viên trong lớp. Bên phải: học viên chưa thuộc lớp.";
            this._lblHuongDanPhanLop.AutoSize = true;
            this._lblHuongDanPhanLop.Padding = new System.Windows.Forms.Padding(4, 9, 16, 0);
            this._gridLop = new System.Windows.Forms.DataGridView();
            this._gridLop.AutoGenerateColumns = true;
            this._gridLop.AllowUserToAddRows = false;
            this._gridLop.AllowUserToDeleteRows = false;
            this._gridLop.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._gridLop.BackgroundColor = System.Drawing.Color.White;
            this._gridLop.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._gridLop.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this._gridLop.ColumnHeadersHeight = 34;
            this._gridLop.Dock = System.Windows.Forms.DockStyle.Fill;
            this._gridLop.EnableHeadersVisualStyles = false;
            this._gridLop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._gridLop.GridColor = System.Drawing.Color.FromArgb(213, 220, 230);
            this._gridLop.MinimumSize = new System.Drawing.Size(320, 180);
            this._gridLop.MultiSelect = false;
            this._gridLop.ReadOnly = true;
            this._gridLop.RowHeadersVisible = false;
            this._gridLop.RowTemplate.Height = 30;
            this._gridLop.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._gridTrongLop = new System.Windows.Forms.DataGridView();
            this._gridTrongLop.AutoGenerateColumns = true;
            this._gridTrongLop.AllowUserToAddRows = false;
            this._gridTrongLop.AllowUserToDeleteRows = false;
            this._gridTrongLop.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._gridTrongLop.BackgroundColor = System.Drawing.Color.White;
            this._gridTrongLop.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._gridTrongLop.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this._gridTrongLop.ColumnHeadersHeight = 34;
            this._gridTrongLop.Dock = System.Windows.Forms.DockStyle.Fill;
            this._gridTrongLop.EnableHeadersVisualStyles = false;
            this._gridTrongLop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._gridTrongLop.GridColor = System.Drawing.Color.FromArgb(213, 220, 230);
            this._gridTrongLop.MinimumSize = new System.Drawing.Size(320, 180);
            this._gridTrongLop.MultiSelect = false;
            this._gridTrongLop.ReadOnly = true;
            this._gridTrongLop.RowHeadersVisible = false;
            this._gridTrongLop.RowTemplate.Height = 30;
            this._gridTrongLop.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._gridNgoaiLop = new System.Windows.Forms.DataGridView();
            this._gridNgoaiLop.AutoGenerateColumns = true;
            this._gridNgoaiLop.AllowUserToAddRows = false;
            this._gridNgoaiLop.AllowUserToDeleteRows = false;
            this._gridNgoaiLop.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._gridNgoaiLop.BackgroundColor = System.Drawing.Color.White;
            this._gridNgoaiLop.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._gridNgoaiLop.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this._gridNgoaiLop.ColumnHeadersHeight = 34;
            this._gridNgoaiLop.Dock = System.Windows.Forms.DockStyle.Fill;
            this._gridNgoaiLop.EnableHeadersVisualStyles = false;
            this._gridNgoaiLop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._gridNgoaiLop.GridColor = System.Drawing.Color.FromArgb(213, 220, 230);
            this._gridNgoaiLop.MinimumSize = new System.Drawing.Size(320, 180);
            this._gridNgoaiLop.MultiSelect = false;
            this._gridNgoaiLop.ReadOnly = true;
            this._gridNgoaiLop.RowHeadersVisible = false;
            this._gridNgoaiLop.RowTemplate.Height = 30;
            this._gridNgoaiLop.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._txtTenLop = new System.Windows.Forms.TextBox();
            this._txtTenLop.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtTenLop.BackColor = System.Drawing.Color.White;
            this._txtTenLop.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTenLop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtTenLop.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtTenLop.Margin = new System.Windows.Forms.Padding(4);
            this._txtTenLop.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtTenLop.Width = 220;
            this._txtTrinhDo = new System.Windows.Forms.TextBox();
            this._txtTrinhDo.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtTrinhDo.BackColor = System.Drawing.Color.White;
            this._txtTrinhDo.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTrinhDo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtTrinhDo.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtTrinhDo.Margin = new System.Windows.Forms.Padding(4);
            this._txtTrinhDo.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtTrinhDo.Width = 220;
            this._txtLichHoc = new System.Windows.Forms.TextBox();
            this._txtLichHoc.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this._txtLichHoc.BackColor = System.Drawing.Color.White;
            this._txtLichHoc.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtLichHoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._txtLichHoc.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this._txtLichHoc.Margin = new System.Windows.Forms.Padding(4);
            this._txtLichHoc.MinimumSize = new System.Drawing.Size(150, 0);
            this._txtLichHoc.Width = 220;
            this.root = new System.Windows.Forms.TableLayoutPanel();
            this.form = new System.Windows.Forms.TableLayoutPanel();
            this.form.AutoSize = true;
            this.form.BackColor = System.Drawing.Color.White;
            this.form.ColumnCount = 4;
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.form.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.form.Dock = System.Windows.Forms.DockStyle.Top;
            this.form.GrowStyle = System.Windows.Forms.TableLayoutPanelGrowStyle.AddRows;
            this.form.Margin = new System.Windows.Forms.Padding(0);
            this.form.Padding = new System.Windows.Forms.Padding(12, 10, 12, 10);
            this.buttons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnThem = new System.Windows.Forms.Button();
            this.btnThem.AutoEllipsis = true;
            this.btnThem.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnThem.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThem.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnThem.Height = 34;
            this.btnThem.Margin = new System.Windows.Forms.Padding(4);
            this.btnThem.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnThem.UseVisualStyleBackColor = false;
            this.btnThem.Width = 110;
            this.btnThem.Text = "Thêm mới";
            this.btnLuu = new System.Windows.Forms.Button();
            this.btnLuu.AutoEllipsis = true;
            this.btnLuu.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnLuu.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuu.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLuu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLuu.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnLuu.Height = 34;
            this.btnLuu.Margin = new System.Windows.Forms.Padding(4);
            this.btnLuu.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnLuu.UseVisualStyleBackColor = false;
            this.btnLuu.Width = 110;
            this.btnLuu.Text = "Lưu";
            this.btnXoa = new System.Windows.Forms.Button();
            this.btnXoa.AutoEllipsis = true;
            this.btnXoa.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnXoa.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnXoa.Height = 34;
            this.btnXoa.Margin = new System.Windows.Forms.Padding(4);
            this.btnXoa.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnXoa.UseVisualStyleBackColor = false;
            this.btnXoa.Width = 110;
            this.btnXoa.Text = "Xóa";
            this.bottom = new System.Windows.Forms.Panel();
            this.split = new System.Windows.Forms.TableLayoutPanel();
            this.assignButtons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnThemHv = new System.Windows.Forms.Button();
            this.btnThemHv.AutoEllipsis = true;
            this.btnThemHv.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnThemHv.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnThemHv.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnThemHv.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThemHv.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnThemHv.Height = 34;
            this.btnThemHv.Margin = new System.Windows.Forms.Padding(4);
            this.btnThemHv.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnThemHv.UseVisualStyleBackColor = false;
            this.btnThemHv.Width = 110;
            this.btnThemHv.Text = "Thêm vào lớp";
            this.btnXoaHv = new System.Windows.Forms.Button();
            this.btnXoaHv.AutoEllipsis = true;
            this.btnXoaHv.BackColor = System.Drawing.Color.FromArgb(235, 242, 252);
            this.btnXoaHv.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoaHv.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnXoaHv.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnXoaHv.ForeColor = System.Drawing.Color.FromArgb(31, 41, 55);
            this.btnXoaHv.Height = 34;
            this.btnXoaHv.Margin = new System.Windows.Forms.Padding(4);
            this.btnXoaHv.Padding = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.btnXoaHv.UseVisualStyleBackColor = false;
            this.btnXoaHv.Width = 110;
            this.btnXoaHv.Text = "Xóa khỏi lớp";
            this.root.SuspendLayout();
            this.form.SuspendLayout();
            this.buttons.SuspendLayout();
            this.bottom.SuspendLayout();
            this.split.SuspendLayout();
            this.assignButtons.SuspendLayout();
            this.SuspendLayout();

            this.root.Dock = System.Windows.Forms.DockStyle.Fill;
            this.root.RowCount = 4;
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55F));

            this.buttons.AutoSize = true;
            this.buttons.Controls.Add(this.btnThem);
            this.buttons.Controls.Add(this.btnLuu);
            this.buttons.Controls.Add(this.btnXoa);

            this.form.Controls.Add(this._lblDesigner1, 0, 0);
            this.form.Controls.Add(this._txtTenLop, 1, 0);
            this.form.Controls.Add(this._lblDesigner2, 2, 0);
            this.form.Controls.Add(this._txtTrinhDo, 3, 0);
            this.form.Controls.Add(this._lblDesigner3, 0, 1);
            this.form.Controls.Add(this._txtLichHoc, 1, 1);
            this.form.Controls.Add(this.buttons, 3, 1);

            this.split.Dock = System.Windows.Forms.DockStyle.Fill;
            this.split.ColumnCount = 2;
            this.split.RowCount = 1;
            this.split.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.split.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.split.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.split.Controls.Add(this._gridTrongLop, 0, 0);
            this.split.Controls.Add(this._gridNgoaiLop, 1, 0);

            this.btnThemHv.Width = 130;
            this.btnXoaHv.Width = 130;
            this.assignButtons.Dock = System.Windows.Forms.DockStyle.Top;
            this.assignButtons.AutoSize = true;
            this.assignButtons.Padding = new System.Windows.Forms.Padding(8);
            this.assignButtons.Controls.Add(this._lblHuongDanPhanLop);
            this.assignButtons.Controls.Add(this.btnThemHv);
            this.assignButtons.Controls.Add(this.btnXoaHv);

            this.bottom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottom.Controls.Add(this.split);
            this.bottom.Controls.Add(this.assignButtons);

            this.btnThem.Click += this.BtnThem_Click;
            this.btnLuu.Click += this.BtnLuu_Click;
            this.btnXoa.Click += this.BtnXoa_Click;
            this.btnThemHv.Click += this.BtnThemHv_Click;
            this.btnXoaHv.Click += this.BtnXoaHv_Click;
            this._gridLop.SelectionChanged += this.GridLop_SelectionChanged;
            this.root.Controls.Add(this._lblTitle, 0, 0);

            this.root.Controls.Add(this.form, 0, 1);
            this.root.Controls.Add(this._gridLop, 0, 2);
            this.root.Controls.Add(this.bottom, 0, 3);

            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 720);
            this.Name = "FrmLopHoc";
            this.Controls.Add(this.root);

            this.root.ResumeLayout(false);
            this.root.PerformLayout();
            this.form.ResumeLayout(false);
            this.form.PerformLayout();
            this.buttons.ResumeLayout(false);
            this.bottom.ResumeLayout(false);
            this.bottom.PerformLayout();
            this.split.ResumeLayout(false);
            this.assignButtons.ResumeLayout(false);
            this.assignButtons.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
    }
}
